### ISSUE TITLE
Running cinch in python ~3.6 venv fails with import module error

### ISSUE THREAD

**Issue by Dannyb48** [RedHatQE/cinch#254]
I install cinch in a python 3.6 virtulenv and when I run `--help` i get the following error

```
cinch --help
Traceback (most recent call last):
  File "/home/dbaez/.virtualenvs/jenks_cinch/bin/cinch", line 5, in <module>
    from cinch.bin.entry_point import cinch
  File "/home/dbaez/.virtualenvs/jenks_cinch/lib/python3.6/site-packages/cinch/bin/entry_point.py", line 4, in <module>
    from wrappers import call_ansible
```

**Comment by greg-hellings** [comment]
You'll want to tag and release
