### ISSUE TITLE
systemd swarm service is unable to write to /home/jenkins

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#50]
```
Building remotely on cinch-slave-c37471bc (cinch-slave swarm) in workspace /home/jenkins/workspace/jslave-cinch-test-2-runtest
java.io.IOException: Failed to mkdirs: /home/jenkins/workspace/jslave-cinch-test-2-runtest
	at hudson.FilePath.mkdirs(FilePath.java:1169)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Archiving artifacts
ERROR: Build step failed with exception
/home/jenkins/workspace/jslave-cinch-test-2-runtest does not exist.
```

**Comment by greg-hellings** [comment]
Is this one fixed for now? Can we close it?

**Comment by robled** [comment]
Yeah, fixed!
